[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paymobz"
version = "0.16"
description = "Unofficial Python SDK for Paymob payment gateway (Unified Checkout, Intention, Iframe)"
readme = "README.md"
requires-python = ">=3.8"

authors = [
    { name = "Ahmed Saoud", email = "ahmedsaoud0work@gmail.com" }
]

license = { text = "MIT" }

dependencies = [
    "httpx>=0.24.0"
]

keywords = [
    "paymob",
    "payments",
    "sdk",
    "egypt",
    "checkout"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["paymobz*"]